### ISSUE TITLE
if bug

### ISSUE THREAD

**Issue by Farcek** [mbosecke/pebble#46] opened 2014-11-26 05:30 UTC
always else tag runing
/*****************************/

{% if(v == 1)%}
    ...
{% elseif(v == 2)%}
   ...
{% elseif(v==3)%}
  ...
{% else %}
... // the always running
{% endif%}

**Comment by nhylated** [comment] 2015-01-11 13:09
Hi,

This issue is reproducible with float and doubles and sometimes with integers as well. The issue was due to == being used for comparing two Number objects. The underlying issue is the one discussed [here](http://stackoverflow.com/questions/12226757/).

I've created pull request #53 for this along with a regression test. Let me know if you need anything else in the pull request.

Thanks.

**Comment by mbosecke** [comment] 2015-01-12 17:16
Resolved by pull request #53

**Closed by mbosecke** 2015-01-12 17:16 UTC
Labels: bug
